---
title: "News for package `sbwtools`"
author: "Author: S. Bryan West<br>"
date: "Updated `r format(Sys.time(), '%d %B, %Y')`"
output: 
  github_document:
    html_preview: true
  # md_document:
    # variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/NEWS-",
  out.width = "100%"
)
```
## v.0.0.1.3.02

This is for the `dev` branch **only**.

  - Created a `packages.R` template file, called with `use_packages` function.

## v.0.0.1.3

  - Added function to create `analysis_data` and `original_data` directories.

## v0.0.1.2
  
  - Added a document template for course labs and homework assignments

## v0.0.1.1

  - Added function to create standard directories I use with most projects

## v0.0.1.0

  - Removed `install_load_packages`. Replace with 
  [`pacman` (github link)](https://github.com/trinker/pacman).


## v0.0.0.9004

Note: I downgraded the version number from 0.0.1 to 0.0.0.9004 because this package
is not a stable or final release and is still under active development.

  - Added NEWS (this document).

  - Updated `format_pval` to allow optional suppression of leading zeros and to
  use significant digits (e.g., .010 instead of 0.01).
  
  - Updated `make_forest_plot` to place axis labels within `labs()` section
  instead of as `xlab` and `ylab`.
  
  - Deprecated `install_load_packages`. Replace with 
  [`pacman` (github link)](https://github.com/trinker/pacman).
  
  - README updated to credit authors of functions I have borrowed and modified.
